### ISSUE TITLE
Go release-drafter's APIdiff is acting weird.

### ISSUE THREAD

**Issue by bendiknesbo** [coopnorge/github-workflow-release-drafter#12]
When running `apidiff` against https://github.com/coopnorge/go-datadog-lib, it does not pick up all of the API.

In #11, I changed the argument to `apidiff` from `.` to `./...`, to allow `apidiff` to run when there was no Go-files in the root-directory.

When testing further, I manually inspected the output from `apidiff -w old.txt ./...`, and saw that only a small part of the API in https://github.com/coopnorge/go-datadog-lib was present in `old.txt`.

We need to fix the invocation of `apidiff`, or move to another tool that can give us a proper API-diff.

**Comment by bendiknesbo** [comment]
Some further investigation makes it seem like we should be using the `-m` flag to compare the module, and not a single package, but this requires more investigation.

**Comment by arunpoudel** [comment]
@bendiknesbo Looks like that is what is needed.

A module is able to contain packages in subdirectories.
(See)[https://cs.opensource.google/go/x/exp/+/7918f672:apidiff/apidiff.go;l=97]
